### ISSUE TITLE
Support for oauth2-proxy frontend?

### ISSUE THREAD

**Issue by anannaya** [sipcapture/homer-app#497]
https://github.com/oauth2-proxy/oauth2-proxy  is widely used in many projects ,  Which intern sets some header along Authorization bearer token , Can the homer be supported with id_token ?

**Comment by lmangani** [comment]
Homer already supports oauth2

https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json#L149

**Comment by adubovikov** [comment]
as I understood it correct, this oauth2-proxy needs only in case if your application doesn't support SSO, which is not our case, because homer-app has full support oauth2. I will open the ticket open, but this is a feature request which VERY specific for your scenario. Feel free make a PR to implement this feature.

**Comment by anannaya** [comment]
@adubovikov  Not example there are some apps like grafana,kiali supports Header based login is and roles are assigned. But in out case homer just need to process the Authorization bearer header and login. 
For example 
```
    auth.proxy:
      auto_assign_org_role: Editor
      auto_sign_up: true
      enabled: true
      header_name: X-Auth-Request-Email
```
